name: Paint_au_chocolat

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  SOURCE: OrionPX4k/intro-to-chocolatine
  MIRROR_URL: "EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-thomas.lebouc"
  EXECUTABLES: "replace_vowel"
  GITHUB_SSH_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: give rigth && checking coding-style
      run: chmod +x ./bash_shell/check.sh; ./bash_shell/check.sh $(pwd) $(pwd)
    - name: check result
      run: chmod +x ./bash_shell/checker_bash.sh; ./bash_shell/checker_bash.sh && exit  $? || exit 1
